### ISSUE TITLE
Temporal local activities not being created

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1022]
Temporal local activities are never being created.  This means that the local activity execution request never comes through to the proxy, failing the workflow with a decision task time out.

**Comment by jefflill** [comment]
I took a quick look at this one and it appears that the .NET side generates local activity stubs by the same as we did for Cadence and that the stubs should send an `ActivityExecuteLocalRequest` message when the activity is executed.  I tried running the unit test but it looks like the proxy is having trouble connecting to Temporal when it's not in DEBUG mode.

I'm seeing a **"proxy"** error back from the proxy which looks like a new error, so my error handling code is throwing a `NotImplementedException` because it doesn't know what this is.  Perhaps the new error is do to the error/retry changes you mention Temporal made just before shipping.

**Comment by johncburns1** [comment]
Yeah they totally reworked the entire way errors work as well as the errors themselves.  There are only like 3 that are the same.  I added a proxy error because I am not really sure yet what to use as a reasonable default so I am defaulting to a proxy error for now until I can take a deeper look at errors and error handling.

**Comment by jefflill** [comment]
**CLOSING:** Temporal is deprecated
