### ISSUE TITLE
Temporal workflow execution blocked by mutex deadlock

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1068]
Implemented the `NewWorker`/`StartWorker` fix described in #1018.  I continued with testing and found that once a workflow is started, the execution is blocked by a deadlock in the Neon.Temporal library.  

The deadlock occurs when the Temporal client attempts acquire the `workerMutex` to get the workflow registration on line **269** in `Neon.Temporal\Worker.Workflows`.  This happens trying to resolve an incoming `WorkflowInvokeRequest` from the Temporal proxy and `OnIvokeAsync()` is called.  The `OnInvokeAsync()` method attempts to retrieve the workflow registration by calling the function `GetWorkflowRegistrationAsync()` on line **370** in  `Neon.Temporal\Worker.Workflows`.  Within that `GetWorkflowRegistrationAsync()` method is where the deadlock occurs.

**Comment by jefflill** [comment]
You know, I'm not entirely sure that we actually need this mutex, especially after the worker has started.  I believe this is protecting the workflow implementation registrations from multi-thread operations but this dictionary becomes effectively read-only after the worker is started because no more registrations will be allowed thereafter.  So we really only need to protect the dictionary while registering workflow implementations on the off chance that somebody is doing this on multiple threads.

I'm going to look into honoring the mutex only for registration operations and also ensuring that registrations can't happen after the worker has been started (which I believe we already do).  This will also improve runtime performance some.

The same thing may apply to activity workers.

**Comment by jefflill** [comment]
The underlying cause here is that `await AsyncMutex.AcquireAsync()` **is not** a drop-in replacement for `lock (...)` because nested locks are re-entrant and will succeed and `AsyncMutex` is not re-entrant.
```
var o = new object();

lock (o)
{
    lock (o) // <-- this doesn't deadlock
    {
    }
}

var mutex = new AsyncMutex();

using (await mutex.AcquireLock())
{
    using (await mutex.AcquireLock())  // <-- this deadlocks
    {
    }
}
```
I should have remembered this because I wrote the `AsyncMutex` class years ago.

**Comment by johncburns1** [comment]
You know when I learned about deadlock in class I never thought that I would actually deal with it as much as I do.  I guess that's what you sign up for when dealing with async programming.

**Comment by jefflill** [comment]
Yeah well, threading in general.

So, I removed the mutex and reverting back to locks, finer grained this time to protect only the variables that actually need it for the given operation.  This worked for a simple workflow unit test but unfortunately not for the correspondingly simple activity test case.

I know you mentioned that Temporal changed the error/retry model.  I'm seeing error strings like **"proxy"** and **"application"** now and rather than throwing a `NotImplementedException`, I'm converting these to **"custom"** errors for now.
