### ISSUE TITLE
Cadence/Temporal don't work on .NET 5

### ISSUE THREAD

**Issue by iain-cyborn** [nforgeio/neonKUBE#1073]
I tried Neon.Temporal as a dependency of an application targeting .NET 5 and TemporalClient.ConnectAsync() throws an exception for "Unsupported .NET framework: Unknown".
Are there plans to support .NET 5?

**Comment by jefflill** [comment]
Interesting.  All of the public Neon libraries are .NET Standard 2.0 except for Neon.Web which is .NET Standard 2.1, so in theory this should have just worked for a .NET 5 app.  We haven't done any testing yet on .NET 5 since it shipped last week but now is as good a time as any; I'll take a look.

BTW: The Temporal client is still very much a work in progress and isn't usable at this time.  We recommend that you start out with Cadence first (although that may very well have the same .NET 5 issue).

**Comment by jefflill** [comment]
This ended up being a problem with detecting the .NET Framework the application is running on.  The **Neon.Cadence** and **Neon.Temporal** clients need to know whether they're running on .NET Framework or .NET Core/5 so it can start the appropriate HTTP server to communicate with the cadence/temporal proxy.  We use `WebListener` for .NET Framework and `Kestrel` for .NET Core/5.

The problem was that the `NeonHelper.Framework` property didn't know how parse the new `RuntimeInformation.FrameworkDescription` value for .NET 5 and beyond (".NET 5.0.0" for .NET 5).  I've corrected this so we should be good until MSFT makes another fundamental change and which hopefully won't be for another decade or two.

**Comment by jefflill** [comment]
@iain-cyborn: I just released this fix for [neonLIBRARY v2.7.0](https://github.com/nforgeio/neonKUBE/releases/tag/release-neonLIBRARY-v2.7.0) and have pushed the updated packages to nuget.org.

As I mentioned above, this was a minor framework detection issue and I've upgraded my unit test projects to .NET 5 so hopefully we'll proactively detect these kind of issues in the future.

We recommend that you start with **Neon.Cadence** if you want to play with workflows.  We've been using it in production for relatively simple workflows for nearly a year now.  **Neon.Temporal** really isn't usable yet but we are actively working on it.  I don't have an ETA for a preview yet though.
