### ISSUE TITLE
[Hyper-V] Memory allocation

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1082]
We are currently using dynamic memory allocation on Hyper-V. @jefflill are we sure we want this by default? Also, the default memory buffer size is set to 20%, which increases the minimum cluster requirements for memory. When we have the min/max set to the same, we basically just lose 20% of allocated RAM (I believe).

![image](https://user-images.githubusercontent.com/11889627/99919903-18c2ae00-2cd5-11eb-81d4-6f5fb56963bd.png)

**Comment by jefflill** [comment]
Yeah, we do want to use dynamic memory for the Local Hyper-V hosting manager (that's by design).  The idea here is that the local Hyper-V manager is intended only for developer workstations and we're betting that clusters will be mostly idle as the user goes about his day doing other things on his/her computer.  So we'd rather not grab all of the RAM upfront and potentially impact the other things the developer is doing.  If they really want to reserve this for some reason, it's easy to uncheck this and restart the nodes.  I believe the default to not be a dog makes sense here.

When/if we implement the regular Hyper-V hosting manager, it will disable dynamic memory and grab all required RAM by default, like we do for XenServer.  That manager will also be able to deploy on remote Windows Services.

I don't remember the **Memory buffer** option.  That may be new.

**Comment by jefflill** [comment]
My read of how **memory buffer** works is that it specified the amount of additional RAM over that the VM is currently using will be allocated to VM.  I believe the idea is to have Hyper-V to watch the actual RAM in use by the VM so that when the VM starts eating into this buffer Hyper-V will try to assign more RAM to get the buffer back up to 20% (or whatever).  I'll bet this is a performance thing for Hyper-V where they probably aren't set up to assign more RAM at the moment where the VM runs out.  Using this buffer, they're trying to proactively ensure that the VM won't run out, at least until it's exceeded the set limit or the host itself is out of RAM.

It wouldn't make sense for Hyper-V to every allocate more RAM to VM than the maximum requested so as the VM approaches this limit, the buffer will be decreased until it's zero when the RAM limit is reached.

The actual issue here is that we're setting **minRAM==maxRAM**.  **minRAM** should probably be set to something smaller, like:

     **min(512 MiB, maxRAM)**

to actually take advantage of the dynamic memory feature.

**Comment by marcusbooyah** [comment]
The memory buffer is causing the Kubernetes scheduler to not schedule pods when it should be. We're going to disable dynamic memory for now.

**Comment by marcusbooyah** [comment]
DONE
