### ISSUE TITLE
Cannot debug in Neon.Temporal

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#1088]
Trying to debug the Neon.Temporal client and the `vsTestRunner` is throwing an exception:
```
System.BadImageFormatException: 'Could not load file or assembly 'testhost, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'
```

This is blocking from debugging issues in the Neon.Temporal Client.

**Comment by jefflill** [comment]
I'm not able to repro this on my workstation (running the `EndToEnd_WorkflowWithNoResult` test, but I am seeing a

 **Neon.Temporal.ConnectException : Cannot connect to Temporal cluster.** 

exception from the proxy.  I tried running Temporal on both Docker/WSL2 and Docker/Hyper-V with the same results.

You didn't include the stack trace in your report but I'll bet the exception is being thrown at `TemporalClient.cs:875` where we launch the **temporal-proxy**.

I wonder if the proxy executable has gotten corrupted somehow.  Can you please try to execute this file manually and see what happens?  If you set a breakpoint at `TemporalClient.cs:875` then the `binaryPath` variable will be the path to the executable.

I was able to manually start the proxy via the command line from the `Build` directory and it started OK for me.

I wonder if something wonky happened with the proxy build on your machine.  It is possible for proxy executable to be corrupted if the process terminates while the `TemporalClient` is extracting proxy executable and writing it to disk, resulting in the file being truncated.  But, the proxy is always re-extracted and written again the first time a connection is established in a new process and since the executable will be extracted in just a moment, this seems unlikely to be the issue..

But, you should make a note about the size of the extracted proxy executable and compare it against the executable in the `Build` folder just to be sure.

I'm hoping that somehow proxy executable got corrupted somehow during the build and that a clean build will fix it.  I'm now sure what's happening with the connect exception though, but once we get past the corruption issue we can have a look at that.

**Comment by johncburns1** [comment]
Fixed.  I was running projects in tests as x86 architecture.

**Comment by johncburns1** [comment]
Fixed the proxy issue as well.  `DebugPrelaunch` was toggled on in proxy so it was always trying to send replies to `https://127.0.0.1:5001`
