### ISSUE TITLE
Retry k8s apiserver requests

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1144]
Cluster setup will intermittently fail when hitting the k8s apiserver directly using the .NET client. We should retry these operations.

**Comment by jefflill** [comment]
I encountered a somewhat related issue where we'd see an `HttpRequestException` with an inner `SocketException` during cluster setup in debug mode after rebooting the node to pick up some environment variable and perhaps other changes.  The problem was that we were trying to use the k8s client to query the API server before it was able to restart after the node reboot.

I added a retry policy in the setup code to mitigate this.

**Comment by jefflill** [comment]
I completed this a few days ago by generating a wrapper class for the Kubernetes client that implements a retry policy for all methods.
