### ISSUE TITLE
KubernetesWithRetry not generating extension methods

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1161]
Currently we're only generating the `WithHttpMessages` methods present in `IKubernetes`. The official client generates extension methods which just returns the k8s object we care about. This is done in `KubernetesExtensions`. For now in Setup I'm going to use the `WithHttpMessages` methods we're generating so that the retry policy works.

**Comment by jefflill** [comment]
The problem here was that a very large number of the `Kubernetes` client methods are actually defined as extensions in `KubernetesExtensions` rather than in `IKubernetes`.  This seems like a bad practice because it means that folks won't be able to mock these methods in unit tests.

I'm going to address this by reflecting the extension methods as well and generate wrappers for them.

**Comment by jefflill** [comment]
**FIXED**
