### ISSUE TITLE
[neon-cli]: [run] command is ignoring command line options

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#462]
neon run seems to be clipping some commands.

```
neon run -- helm install --name cluster-setup -f ^^^secrets.yaml .\cluster-setup
Error: This command needs 1 argument: chart name
```
I'm not exactly sure what's going on here, it seems like the "--name cluster-setup" isn't being passed to Helm.

The command below works fine (apart from complaining about how secrets.yaml is encrypted) 
```
helm install --name cluster-setup -f secrets.yaml .\cluster-setup
```

**Comment by jefflill** [comment]
This is due to an ancient (as in from 2005) hack I included in the `CommandLine.Shift()` method.

To make the implementation a bit easier, I first shifted all of the command line options to the leftmost side of the command line and then I removed requested number of arguments.  This wasn't a great idea to begin with, because it reordered the commands and options.  But worse it didn't honor the command line splitter with the net result being that the right side command line options also got relocated to the beginning of the command line, effectively removing these options from the right command line.

I've re implemented `CommandLine.Split()` by retaining the order of arguments and options on the left side as well has honoring the splitter (if one was specified).  I also added some additional unit test cases.

**Comment by jefflill** [comment]
We're still having problems with this due to a couple of issues with `NeonHelper.Execute()`:

1. Looks like Windows does not start the sub-process in the current directory.
2. I believe we're seeing a race condition sometimes between reading the sub-process STDERR and STDOUT streams and waiting for the process to exit.

Here's what I did:

1. Set the current directory as `ProcessInfo.WorkingDirectory`
2. Watch for the `null` data items in the in the stream handlers and assume this means that the streams have been flushed and closed before waiting for the process to exit and ultimately disposing it.
