### ISSUE TITLE
Cluster setup gets stuck on tune disks

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#496]

**Comment by marcusbooyah** [comment]
It seems that the /home/sysadmin/.exec folder is being deleted at some point, causing an infinite while loop while setup checks for the exit file in the /home/sysadmin/.exec/cmd/<GUID> folder.

**Comment by jefflill** [comment]
I believe this may be related to the **neon-cleaner** service which is started in [setup-node.sh] just before we do the tune disks.  Perhaps something changed in the Ubuntu 18.04 upgrade because this worked fine for 16.04.

I've temporarily disabled **neonkube-cleaner** service and will come back and investigate further.

**Comment by jefflill** [comment]
The root cause was pruning files using **-mtime +0** like:

`find /dev/shm/neonkube/cmd ! -name . -type d -mtime +0 -exec rm -rf {} \; -prune`

instead of using **-mtime +1** like:

`find /dev/shm/neonkube/cmd ! -name . -type d -mtime +1 -exec rm -rf {} \; -prune`

It's also a bit broken that `SshProxy.RunCommand()` just loops forever when it's `.exec` folder doesn't exist.  I'm going to have the command fail in this case going forward.

**Comment by jefflill** [comment]
FIXED
