### ISSUE TITLE
Neon.Cadence caches [cadence-proxy.exe] such that unit tests don't see updates

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#503]
Test/Neon.Test.Cadence caches cadence-proxy.exe in Test.Neon.Cadence/bin/Debug/netcoreapp3.0.

This makes is such that building the project does not update the go executable when running tests.  When I deleted the Test.Neon.Cadence/bin folder, the exe built again, but was not in the correct format to be executed and caused a terminal failure, so I have been placing my own exe in there for testing purposes.

**Comment by jefflill** [comment]
That makes sense (it’s actually the desirable behavior for production when
the cadence-proxy won’t be changing).

I’ll think about this.  One idea would be to just have debug mode overwrite
this regardless (unless a cadence-proxy instance is already running which
could happen if the application has multiple connections open).  There
might be some other alternatives too.  I’ll get something going in the
morning.

I also think I’ll need to make some tweaks to how the compression works to
ensure that Neon.Cadence imports the new binaries.  Right now, I’m setting
the last modified date of the compressed binaries to the last modified date
of the uncompressed files from the /Build folder.  I should probably set
both the source and compressed last modified times to the current time.

—Jeff

**Comment by jefflill** [comment]
BTW: Good sleuthing, Sherlock.

—Jeff

**Comment by jefflill** [comment]
**FIXED:** I tweaked the **cadence-proxy** binary persistence a bit.  Here's how it works now:

1.  The Neon.Cadence assembly has a static boolean tracking whether the current process has already written the **cadence-proxy** binary.  The steps below are performed only once per process.

2. The correct **cadence-proxy** binary is written to the target file.  It's possible that another instance of the current application is already running making the binary file read-only.  We catch, log, and otherwise ignore this exception, assuming that the existing binary will be correct (which it will be, unless somebody is actively messing with us).

3. Execute access is granted to root and the current user on Linux and OSX.

One additional nice thing about this change is that it supports scenarios where user deploy their application via some kind of installer and then wish to upgrade it in-place.  Previously, the **cadence-proxy** binary would have remained cached and would not have been upgraded along with everything else.  This won't impact Loopie because we'll be deploying as containers, but you never know for the future.

After thinking about it, the `neon-build gzip ...` command is already handling file dates correctly, so no change was necessary here.
