### ISSUE TITLE
XCP-ng: sudo requires tty

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#504]
There is code for disabling this, but it's not working. Need to fix.

Error message: "sorry, you must have a tty to run sudo”

**Comment by jefflill** [comment]
The problem here is that deploying clusters on host machines with new installs of XCP-ng isn't working.  SSH.NET is unable to run commands because the host machine is complaining about the lack of a tty.

@marcusbooyah: _Please put the actual error message here._

...I'm making this a bit more specific in case we run into this again in the future and also for posterity and greater Internet/opensource goodness.

**Comment by marcusbooyah** [comment]
Fixed
