### ISSUE TITLE
import/export cluster login needs cluster definition

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#536]
The cluster definition needs to be included in the export/import.

**Comment by jefflill** [comment]
The problem is that the cluster definitions specifies that state of the cluster at the time it was created but that cluster can be modified over time, so the original definition will become out of date.  The first cluster definition is included in the in the `.neonkube/clusters*.yaml` files but because I needed a place to store this between the cluster pepare and setup steps.

For neonHIVE, I had the **neon-cluster-manager** service periodically rebuild the cluster definition (e.g. looking for new or deleted nodes, update their labels, etc. every 30 seconds or so) and the **neon-cli** would query for to see if the current cluster definition changed before executing every command and downloading the new definition if necessary, before executing the command.

The plan is to do the same thing for neonKUBE but in the meantime, I could include the definition in the export.

- [ ] Include the cluster definition in exported contexts
- [ ] Replace the exported contexts with cluster definitions downloads

**Comment by jefflill** [comment]
The cluster extensions are being persisted to the output.  The problem is that this is not being imported.

**Comment by jefflill** [comment]
FIXED.
