### ISSUE TITLE
Calico setup for > 50 nodes

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#547]
https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/calico

**Comment by jefflill** [comment]
Hmmm.  This note mentions that we **won't need Typha** and do a different configuration if the cluster is deployed using etc rather than the **Kubernetes API Datastore** because etc is already optimized for handling **many clients**:

https://github.com/projectcalico/typha

I thought that we're already deploying etc for this and I'm not entirely sure how the **Kubernetes API Datastore** is different from etc.  Perhaps the Calico etc is somehow different from the Kubernetes API etc?

**Comment by jefflill** [comment]
This looks like it's still a thing.

I recommend that we go with their 50+ node configuration with for neonKUBE clusters created with something like 10 (maybe 20) nodes.  The logic is that folks may scale their cluster later to 50+ nodes and that clusters created with <= 10 nodes will be unlikely to scale past this.

This could be the default behavior and the we could add a cluster definition property explicitly controlling this.

**Comment by marcusbooyah** [comment]
We're going to use Cilium in the future, so this goes away
