### ISSUE TITLE
[cadence]: ConnectRequest message does not parse [ClientTimeout]

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#549]
It looks like the **cadence-proxy** is not parsing the `ClientTimeout` property (or you haven't pushed your latest changes of to the **cadence** branch to GitHub).

**Comment by johncburns1** [comment]
I'll change that. When Removed the ProxyRequest timeout I changed the
timeout to a constant for testing and need to change it back.

**Comment by johncburns1** [comment]
ClientTimeout is now being set.  The ConnectRequest itself takes the longest to complete (because it has to wait on the cadence-server to begin accepting requests, so I have the default value set to 30 seconds.  I get the ClientTimeout value from the ConnectRequest, establish a connection to the cadence server using the default 30 second timeout, and then set the ClientTimeout value after the connection is established.  All following requests will have the timeout specified by the ConnectRequest ClientTimeout property.
