### ISSUE TITLE
Cadence: Register domain issue

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#565]
Registering a domain with the cadence server can take a little bit of time, and starting the workflow can fail because it tries to start on a domain that does not exist in cadence yet.  Maybe when we register a domain, we can wait to send a response back from the proxy until it has been polled to make sure that it exists in the server still.

**Comment by jefflill** [comment]
Yeah, we're probably seeing this because the `CadenceFixture` is is spinning up a new **cadence-test** docker container immediately before the first unit test runs and I'll bet the Cadence server isn't quite ready.  Here's what I'd do to workaround this when you're executing a workflow or activity:

1. Try executing the workflow or activity.
2. You're done if there's no error.
3. If there's an entity not found error and it's indicating that its a missing domain, then sleep for a second.
4. Then try again.
5. Repeat steps 3-4 another up to 4 times.

The net effect will be that the first call will almost always work on production clusters because they will have been started long ago and the domain will probably have been setup by devops.  The behavior when the domain doesn't exist will be semantically the same, but you will have tried the operation 5 times with a second delay between retries, so the impact will be that it'll take an extra 4 seconds for the app to actually see the error.

This seems like a reasonable trade off.

**Comment by johncburns1** [comment]
I created a temporary fix for this.  I do not think that this case will ever come up in production.
I do the following whenever I execute a workflow:
```
var workflowRun client.WorkflowRun
	var err error
	for i := 0; i < 3; i++ {
		workflowRun, err = helper.WorkflowClient.ExecuteWorkflow(ctx, options, workflow, args...)
		if err != nil {

			if strings.Contains(err.Error(), "EntityNotExistsError{Message: Domain:") {
				time.Sleep(time.Second)
				continue
			}

			// $debug(jack.burns)
			helper.Logger.Error("failed to create workflow", zap.Error(err))
			return nil, err
		}

		break
	}
```
