### ISSUE TITLE
Cadence: Signals aren't working

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#568]
@johncburns1: I've implemented the first simple workflow signal unit test: `Test_EndToEnd.Workflow_Signal_Simple`.

I fixed a few related issues on the .NET side but I never get a `WorkflowSignalInvokeRequest` from the **cadence-proxy**.  It looks like I'm sending the `WorkflowSetSignalHandlerRequest` properly and the proxy is replying without error.

**NOTE:** You can temporary increase `maxWaitSeconds` value in the unit test to prevent the workflow from timing out while you're debugging.

**Comment by johncburns1** [comment]
I'll check this out. With the new model, are multiple clients supported? Also is the domain registration a bug that should be reported?

**Comment by jefflill** [comment]
I'm not sure about how the API model will play out.  For the next few days, let's concentrate on getting all of the interactions between the client and proxy working and then I figure we'll pop up out of the weeds and take a closer look at the big picture and figure what it would take to more closely align with the Java API.

The thing though, is that I expect that these .NET client API surface area changes will have little or no impact on the **cadence-proxy**.

I wouldn't bother submitting the domain registration issue since they'll probably say its by design and our (testing) use case won't really ever happen in production (since domains will typically be registered long in advance of the first workflow submitted to it).  And besides, our workaround is very seamless.

**Comment by johncburns1** [comment]
OK. I have a few minor changes to make that I will push once complete and I will let you know so that you can then merge into your work. I do need to find a way to poll upon workflow execution because i can see having to keep increasing the number of tries for creating a workflow. I have already had to do it once. Let me know if you have any ideas on that. What I could do is just have an infinitely large number of iterations in the loop and since the ExecuteWorkflow call takes a context with a timeout, then it might just be good to wait for that timeout, because if the domain doesn't exist anyway, then it is going to error out anyway, but I guess the issue is that if the domain actually does not exist, you will not get that error.

**Comment by johncburns1** [comment]
I need to think about that actually. Right now if the domain actually doesn't exist, you will never know because I am essentially ignoring the case.

**Comment by jefflill** [comment]
**FIXED:** This ended up being a race condition caused by the .NET side.  The workflow `OnInvokeAsync()` handler was registering the query and signal handlers too early, before initializing the workflow mapping tables, resulting in the possibility that a pending signal could get invoked and then fail to be handled because it wasn't able to locate the workflow since these tables weren't up-to-date.
