### ISSUE TITLE
A "Neon.Windows.PowerShellException" is thrown if the VMware PowerCLI PowerShell module is installed

### ISSUE THREAD

**Issue by icnocop** [nforgeio/neonKUBE#571]
Hi.

Thank you for neonKUBE.

A "Neon.Windows.PowerShellException" is thrown if the VMware PowerCLI PowerShell module is installed.

It's similar to this issue: https://github.com/kubernetes/minikube/issues/2226

The VMware and Hyper-V PowerShell modules have conflicting cmdlets like Get-VM.

Calls to the Hyper-V PowerShell cmdlets should be prepended with "Hyper-V\\" like "Hyper-V\Get-VM" to avoid conflicts.

Steps to reproduce:
1. Install the VMware PowerCLI PowerShell module
` Install-Module -Name VMware.PowerCLI`
See https://www.powershellgallery.com/packages/VMware.PowerCLI for more information.

2. Run the following code:
```
HyperVClient client = new HyperVClient();
client.ListVMs();
```

Result:
```
Neon.HyperV.HyperVException:  ---> Neon.Windows.PowerShellException:
   at Neon.Windows.PowerShell.ExecuteJson(String command, Boolean noEnvironmentVars)
   at Neon.HyperV.HyperVClient.ListVMs()
```

Thank you.

**Comment by jefflill** [comment]
**HELLO!:** You should probably win a prize or something; you're the first external person to post an issue on the repo since I made it public earlier this year.

This looks like an easy fix, I wasn't aware that you could use a "namespace" prefix like this in Powershell.  I'll look at fixing this today and committing it to the **master** branch and probably do a binary release early next week.

Please note that we're still in very active development on all of this.  We've been focused on implementing a .NET Cadence library for the [Uber Cadence Workflow Server](https://cadenceworkflow.io/docs/) for the past 2-3 months but will be popping back up to get the Kubernetes stuff into a usable state.

The neonKUBE Desktop app is very broken right now and we'll be making some potentially breaking changes in the next month or so.  But, we'll need this to start stabilizing this soon because we have another private project that we need to deploy in production by mid-August.  So, I expect that we'll have a formal preview by then at the latest and of course, we'll still be doing alpha releases in the meantime.

**Comment by jefflill** [comment]
**FIXED**
