### ISSUE TITLE
[ModelGen] __O being serialized

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#633]
Here's a couple of examples where the JObject is being serialized:

```json
{
  "Id": "KF9VucDr3kin1Y5PMV1aXQ",
  "FirstName": "Marcus",
  "LastName": "Bowyer",
  "Phone": "+1-2047894561",
  "Email": "marcus@loopie.io",
  "Emails": [
    {
      "__JObject": {},
      "Address": "marcus@loopie.io"
    }
  ],
  "__T": "u",
  "LastActive": "2019-08-23T18:02:56.1626927Z"
}
```

```json
{
  "__T": "p2s",
  "__JObject": {},
  "Id": "98112",
  "ServiceAreas": [
    "SSA0",
    "SSA2",
    "SSA1"
  ]
}
```

**Comment by jefflill** [comment]
For now, the plan is to strip out all of these properties before persisting data to the database.

I'm also going to rename: `__JObject --> __O`

**Comment by jefflill** [comment]
I just noticed something important: The root object's `__O` property will be `null` after serializing it.  The problem is that the generated `ToJObject()` methods actually returns the `__O` property of the data object being converted which will never have an `__O` property itself since it **is** the `__O` property.

**Comment by jefflill** [comment]
I believe the secondary issue in #698 where the conditional was inverted was causing the root `__O` property to never be initialized because the round trip serializer wasn't being used.

**Comment by jefflill** [comment]
I re-thought the implementation for this over the weekend.  I believe the better approach is to never serialize the `__O` properties separately and implement custom serialization that walks the object hierarchy calling `__Save()` on `IRoundtripData` objects and then persisting the properties from `__O` instead of letting JSON.NET serialize the real properties.  We'd also have to implement custom parsing.

I believe I can do all of this with limited additional processing and object allocation overhead.

**Comment by jefflill** [comment]
I added a `[JsonIgonore]` to the generated `__O` properties so these will no longer be serialized

Remaining work: We need to re-code serialization to make round tripping work.

**Comment by jefflill** [comment]
I'm also temporarily disabling some round trip code generation and will come back to this later: #704
