### ISSUE TITLE
cadence-proxy logging with client-id=0

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#644]
.NET client needs to handle log messages specially by ignoring `clientId == 0`.

**Comment by johncburns1** [comment]
Just a note for testing.  Because of this issue, tests will only pass when running with `DebugPrelaunched = false` if the `LogLevel  == None`.  This is because `LogLevel.None` this skips the `Write()` step of the custom logger interface.  With no cadence client @ `ClientId = 0`, the proxy will hang forever because the .NET client will never return a `LogReply` to the cadence-proxy's `LogRequest`.

**Comment by johncburns1** [comment]
Testing will work when `DebugPrelaunched == true` and `Debug == true`.

**Comment by jefflill** [comment]
**FIXED**
