### ISSUE TITLE
External activity completion and heartbeats

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#654]
We need to complete this implementation and add some unit tests:

- [x] Convert `taskToken` values from a byte array to a base-64 encoded string.  This will make it easier to persist these to databases, etc.

- [x] Finalize how activities indicate that they won't complete on return.  Java provides the `Activity.doNotCompleteOnReturn()` method.  We should probably do the same and get rid of the special `CadenceActivityExternalCompletionException` exception.

**Comment by jefflill** [comment]
@johncburns1: Three activity unit tests using tokens are failing:

- [ ] **Test_EndToEnd.ActivityExternalCancelByToken**
- [ ] **Test_EndToEnd.ActivityExternalErrorByToken**
- [ ] **Test_EndToEnd.ActivityExternalCompleteByToken**

**Comment by johncburns1** [comment]
On it Charlie.

**Comment by johncburns1** [comment]
FIXED. I had to add an optional `string domain = null` parameter to the external activity completion methods that take a `TaskToken`.  This is because we are using the domain to keep track of `WorkflowClient` instances on the cadence-proxy side.  Even though domain is not used in the actually `workflowClient.CompleteActivity()` call, it is used to determine which `WorkflowClient` instance will make the call.
