### ISSUE TITLE
Entity ID should be a key

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#703]
Change so that Entity ID is always a key, and the GetKey/CreateKey methods are smart about not adding a key to a string that already contains one

**Comment by jefflill** [comment]
This issue relates to something we've been wavering on for over a year.  Here's the rundown:

1. Couchbase data entities are persisted using a unique **key** and can be updated, retrieved, or removed using this key.

2. Data entities generally have an ID.  This can be a natural ID like a phone number, or something generated like a sequence number or UUID.

3. As a convention, we're using entity keys formatted like:

  `entity-type::entity-id`

  that combines the entity type with the ID.

4. Often times, one entity needs to reference other entities, e.g. an order referencing the product items included in the order (essentially foreign key references).

Item 4 is the issue.  The question is: **How should entities reference other entities?**

We've been wavering between two answers:

* Entities use the target entity ID as the reference.
* Entities use a target entity key as the reference.

A year+ ago, we decided to reference other entities using just the target entity ID.  The rationale was that the entities would be smaller and easier to read.  The downside was that the any code or queries that need to follow these references would need to implicitly know the type of the target entity so it could generate the full key required to retrieve the target entity.

This has resulted in some confusion and after thinking about it, was kind of a stupid idea.  One problem is that the database doesn't really stand on its own because you can't really look at the database and be able to reason about entity references without already knowing the entity types.

Another way of thinking about this is comparing to how traditional relational databases do foreign key references.  Relation database foreign key references specify the target table as well as the ID of the target record in that table.  In our Couchbase world, the entity type acts somewhat like a relational table, so including the type in our entity reference is conceptually consistent with relational references.

So, we're going to switch to using the entire

**Comment by jefflill** [comment]
**NEVER MIND!**

After looking at the code and discussing this with @marcusbooyah; we realized that we're already doing the right thing here.  So, false alarm.
