### ISSUE TITLE
Documentation for how to use this C# cadence client

### ISSUE THREAD

**Issue by josh-AppSheet** [nforgeio/neonKUBE#711]
I am interested in migrating our c# workflow system to Cadence which I have experience with, in the context of Java.  I was interested in knowing the status of this project and if there is any documentation on implementing the activities and workers in c#.   I realize it is not production-ready yet but would be interested in migrating our code while this project grows. I already know how to start and configure the orchestrator using Docker so docs there is unnecessary.  Sorry if this is not the right place to ask and redirect me as needed.

Thanks!

**Comment by jefflill** [comment]
Hi Josh, we're actively working on this thing and will be probably be upgrading it to **preview** status within a week or so.  The immediate work items remaining are:

* Getting `WorkflowQueue` working so that there's a way for signal methods to interact with the workflow logic.
* Doing a pass at mapping the Cadence related exceptions to something closer to the Java equivalents.
* Implementing Cadence retry options.
* Create a GitHub repo with some samples.

I'm also going to publish a code documentation site soon; maybe as soon as this weekend.

**Comment by josh-AppSheet** [comment]
That sounds great!  Like I said I've used the cadence-java-client library quite a bit, so if you need help with testing or some doc writing or even code contributions I would be happy to help.

**Comment by jefflill** [comment]
Here's what we need to do:

- [ ] Integrate Sandcastle Help File Builder into the build.
- [ ] Deploy this as a GitHub new website
- [ ] Create a new Google Analytics account and insert the code into the generated help pages.
- [ ] Build help as a CHM 
- [ ] Create namespace documentation
- [ ] Create some getting started/overview documentation pages
- [ ] Update the project **README.md** pages to link over to the corresponding namespace on the documentation site.
- [ ] Create a samples GitHub repo
- [ ] Verify that the samples work on OS/X too.

**Comment by jefflill** [comment]
@josh-AppSheet: Sorry about the delay on this.  I'm actively working on documentation but been a bit slammed on my day job.  I should be able to do a proper release within a week (perhaps sooner).

**Comment by jefflill** [comment]
@josh-AppSheet: I've release version 1.0.0 of this thing.  It works on Windows and Linux.  I need to do some debugging on OS/X.  Here are links to the documentation and samples:

[https://doc.neonkube.com/](https://doc.neonkube.com/)
[https://github.com/nforgeio/cadence-samples](https://github.com/nforgeio/cadence-samples)
