### ISSUE TITLE
how to call remote/external workflow

### ISSUE THREAD

**Issue by kaiverge** [nforgeio/neonKUBE#788]
Dear Neon.Cadence development team,

I cannot figure out how to the following:

From Server A, I need to call workflows from Server B. Not to create a new workflow, just to call workflow from remote server so it starts executing on that server.

e.g. what im trying to do:

//THIS CODE RUNS ON SERVER A try { var settings = new CadenceSettings("cadence://{IP ADDRESS}") //the IP address of SERVER B { DefaultDomain = "{domain name}", CreateDomain = false };

            using (var client = await CadenceClient.ConnectAsync(settings))
            {
                try
                {

                   //now i need something like this
                     var res = await client.StartWorkflow({workflowID});

                }
                catch (Exception err)
                {
                    var e = err.Message;
                }
how do I implement it? Thank you very much.

**Comment by jefflill** [comment]
I think there may be a misunderstanding of how Cadence works.  The diagram below depicts a typical Cadence deployment.  The GREEN boxes show components and services you'll need to write and deploy and the RED boxes depict the Cadence related services.

![image](https://user-images.githubusercontent.com/4908431/77809325-5985fc80-704c-11ea-9c54-819a790dfb1a.png)

At least one Cadence server instance needs to be deployed and be paired to a Cassandra database (MySQL and I believe Postgres are also supported but we've restricted out self to Cassandra because that's what Uber uses for managing their business and has been battle tested).  Production deployments will typically deploy more than one Cadence servers for scalability and reliability and they'll also typically deploy a cluster of multiple Cassandra servers for the same reasons.

Your `CadenceClient.Connect()` settings will specify the IP address of one or more of the Cadence server instances.  You're essentially connecting to the Cadence cluster and the `CadenceClient` transparently manages communications to the Cadence servers (for example, if one server fails, the client will automatically fail-over to one of the remaining servers).

Let's talk about components you'd be responsible for.  You'll be writing workflows and activities.  These are implemented as interfaces and classes and will need to be deployed and registered as a workflow **worker**.  A worker is simply a .NET program you'll write that establishes a connection to the Cadence cluster and then registers the workflows and/or activities you've written with Cadence.  Cadence uses these registrations to identify which workers implement specific workflows and activities.  You can have multiple workers implementing the same workflow/activities which is great for reliability and scale-out  and you can also deploy workers that implement different sets of workflow/activities, which is nice if you're into microservices (like we are).

You'll also need to implement some kind of application service that starts workflows.  This is often a REST API or website but can be any .NET program.

So here's how this would flow with a simple example.  Let's say you have a simple workflow that called **AddWF** that adds to integers and returns the result.  To make this work, you'd have to:

1. Implement the workflow interface and class in a Worker program.  This program will connect to the Cadence Server when it starts, register the the **AddWF** and start a Cadence worker.  The Cadence  worker essentially tells Cadence that the worker is ready to process any new **AddWF** workflows that are started in the cluster.

  In this diagram, we started the Worker instances, so Cadence will be able to schedule **AddWF** workflows on any of these three instances.

2. Now lets assume that you've got a website that needs to add numbers via a workflow.  This website will also be connected to the Cadence cluster via a `CadenceClient`.

3. When the website needs to execute a workflow, it will create a workflow stub via `CadenceClient.NewWorkflowStub<IWorkflow>()` and then invoke the workflow by calling the it's entry point in the stub.  The stub returns implements `IWorkflow` and acts as a proxy to Cadence and the workflow execution. The `IWorkflow` generic parameter identifies the specific workflow being invoked.  For this example, `IWorkflow` would define an entry point like `int Add(int v1, int v2)` and you'd just call that from your stub.

4. The `CadenceClient` will then call Cadence server to schedule the workflow.  Cadence records this to its database and then invokes the workflow on one of the workers that has registered the workflow.  Note that the website has no control over which worker is invoked.  Cadence chooses workers based on which ones are healthy and are not too busy, etc.  When one of the workers goes offline, Cadence will reschedule any workflows running there to run on one of the remaining healthy workers.

5. The `CadenceClient` running on the worker will receive the workflow invoke request from the Cadence Server.  The client instantiates an instance of the **AddWF** class and calls the same workflow methods you called in the stub, passing the same arguments.  The workflow method does its thing and returns the sum of the two input parameters.

6. After the **AddWF** method returns, the client sends the result back to the Cadence Server, which records the result to the database and returns it to the website.

This is all super basic.  Workflows can call other (child) workflows as well as activities.  Cadence also keeps track of how far multi-step workflows have progressed and can relocate a running workflow to another worker if necessary, re-hydrating it such that will be be in the exact same state as it was before being relocated.  It's also possible to implement and call workflows written in other languages such as GO and Java.

We have some initial documentation describing all of this here:

https://doc.neonkube.com/Neon.Cadence-Overview.htm

and we also have some (somewhat primitive) samples here:

https://github.com/nforgeio/cadence-samples

**Comment by kaiverge** [comment]
Hi,

 

If the workflow and activities are in golang, do you have a sample of C# to call the workflow, and to query its status? In this case the C# code wouldn't provide any services/tasks/workflows, purely just call them.

 

 


 <http://www.vergeag.com/> 

 	
	
 	

 Kai Osmon   |   IT Senior Solution Architect   |   343-367-6661   |    <mailto:kai.osmon@VergeAg.com> kai.osmon@VergeAg.com
