### ISSUE TITLE
If the workflow and activities are in golang, do you have a sample of C# to call the workflow, and to query its status?

### ISSUE THREAD

**Issue by kaiverge** [nforgeio/neonKUBE#790]
If the workflow and activities are in golang, do you have a sample of C# to call the workflow, and to query its status? In this case the C# code wouldn't provide any services/tasks/workflows, purely just call them.

**Comment by jefflill** [comment]
Give me a couple hours.  I'm going to add some topics to the documentation site discussing this as well as your previous question.

**Comment by kaiverge** [comment]
Here is some updates:

Solution: SmartZone.Services

[WorkflowInterface(TaskList = "JDAPIGroup")]
    public interface IJDUserSyncWorkflow : IWorkflow
    {
        /// <summary>
        /// Processes the order.
        /// </summary>
        /// <returns>
        /// <c>true</c> if the order was processed successfully, <c>false</c>
        /// if it was cancelled.
        /// </returns>
        [WorkflowMethod]
        Task<string> JDUserSyncWorkflow(string userID);

        /// <summary>
        /// Attempts to cancel the order.
        /// </summary>
        /// <returns>
        /// <c>true</c> if the order was cancelled, <c>false</c> when it's 
        /// too late to cancel the order.
        /// </returns>
        [SignalMethod("cancel", Synchronous = true)]
        Task<bool> CancelAsync();
    }

 try
            {
                var settings = new CadenceSettings("cadence://00000000")
                {
                    DefaultDomain = "verge-dev",
                    CreateDomain = false
                };

                using (var client = await CadenceClient.ConnectAsync(settings))
                {
                    try
                    {
                        var stub = client.NewWorkflowStub<IJDUserSyncWorkflow>();
                        var orderTask = stub.JDUserSyncWorkflow(userId);

                        var result = await orderTask;

                     
                        Console.WriteLine($"RESULT: {result}");
                    }
                    catch (Exception err)
                    {
                        var e = err.Message;
                        Console.Error.WriteLine(e);
                    }

it works fine except an error message on go side:

, "error": "unable to find workflow type: SmartZone.Services.JDUserSyncWorkflow. Supported types: [JDUserSyncWorkflow, JDOrgSyncWorkflow]"}

The problem is that the full name of the interface is SmartZone.Services.IJDUserSyncWorkflow.

How do I make it to send only IJDUserSyncWorkflow without SmartZone.Services ?

**Comment by kaiverge** [comment]
that was fixed, now another problem:

Im sending cadence a string parameter function(string userid)

userid = "83c299a0-a89f40c598596411b1d8d020"

Cadence return error:

unable to decode the workflow function input bytes with error: unable to decode argument: 0, *string, with json error: json: cannot unmarshal array into Go value of type string, function name: Vergetech.Services.JDUserSyncWorkflow

and what we see was sent on the GO side is:

 [
  "588d71361fc84f9c81602f06cdbfa1b9"
]

what turns "588d71361fc84f9c81602f06cdbfa1b9" into   [
  "588d71361fc84f9c81602f06cdbfa1b9"
]

?

**Comment by jefflill** [comment]
I've completed the documentation updates I mentioned earlier.  You can see this at:

https://doc.neonkube.com/Neon.Cadence-CrossPlatform.htm
https://doc.neonkube.com/Neon.Cadence-Overview.htm

This is actually the first time anybody has tried to use the .NET client for calling a workflow written in GO (including us).  We've been focusing on getting the basics working on .NET.

The .NET client serializes workflow and activity arguments as an array including each argument in the order they appear in the call.  In this case, you have only one argument so we encode the arguments as an array with the single value.  If you passed more arguments, they would have been added to the array.

I wonder if the GOLANG client special cases workflow/activities with only one argument by just serializing it by itself and not using an array.  I'll have to check this out.

**Comment by jefflill** [comment]
One other thing I noticed when I was updating the documentation above, is that it's not currently possible to create a typed stub that can reference existing GOLANG workflows/activities.  The problem is that the .NET client generated workflow/activity type names always include the fully qualified name of the workflow/activity interface definitions and there's currently no way to override this behavior.  GOLANG workflow/activity type names are typically just the name of the implementation function.  I'm going to add the `[WorkflowMethod.CustomTypeName]` and `[ActivityMethod.CustomTypeName]` properties.  When these are set to `true`, the .NET client will ignore the interface names and simply use `[WorkflowMethod.Name]` and `[ActivityMethod.Name]` as the workflow/activity type name (or the actual method name when these properties are `null`).

PS: Sorry for the delay.  I've been distracted for past couple of days (I'm buying a house)

**Comment by kaiverge** [comment]
Thanks for the information Jeff.

 

How is it going with the house? What area? Send me the pic )

 

P.S. Confrats

 


 <http://www.vergeag.com/> 

 	
	
 	

 Kai Osmon   |   IT Senior Solution Architect   |   343-367-6661   |    <mailto:kai.osmon@VergeAg.com> kai.osmon@VergeAg.com

**Comment by jefflill** [comment]
Thanks.  The new place is about 90 miles NE of Seattle near the end of civilization before the mountain pass.  Should be defensible against zombies :)

[house listing](https://www.redfin.com/WA/Sultan/31631-135th-St-SE-98294/home/2624959?utm_source=ios_share&utm_medium=share&utm_campaign=copy_link&utm_nooverride=1&utm_content=link)

I'm heading out for the inspection right now but will be back in the saddle this afternoon.  I'm planing on releasing the v2.0.0 Neon.* packages late next week, hopefully including fixes for your issues and some other changes.

This will be a BREAKING release from the Cadence perspective.  The .NET implementation is a bit of a hack because it actually wraps the GOLANG client and apparently the latest GOLANG client isn't compatible with older Cadence Server releases (I haven't narrowed down what the actual is yet).  Longer term, Maxim is working on a C client and I expect to port to that when it's ready and probably also refactor and simplify the API a bit to correct some hacks we needed to get the GOLANG wrapping to work.

**Comment by kaiverge** [comment]
Very nice house and area and the price is OK )

 


 <http://www.vergeag.com/> 

 	
	
 	

 Kai Osmon   |   IT Senior Solution Architect   |   343-367-6661   |    <mailto:kai.osmon@VergeAg.com> kai.osmon@VergeAg.com

**Comment by jefflill** [comment]
This has been resolved for the [Neon.Cadence v2.0.0](https://github.com/nforgeio/neonKUBE/releases/tag/v2.0.0) release.

**Comment by kaiverge** [comment]
Hi Jeff,

 

Im galdfully yconfirm that the issue was resolved. However I have other question, how do I query status of the workflow?

 

Lets say Im trying to do this:

 

  1 string status;

                       2 WorkflowOptions wfo = new WorkflowOptions();

                       3 wfo.WorkflowId = _appSettings.CadenceStatusWorkFlowIdPrefix + userId;

                       4 wfo.TaskList = _appSettings.CadenceTaskList;

                       5 wfo.WorkflowIdReusePolicy = WorkflowIdReusePolicy.AllowDuplicate;

 

                       6 var stub = client.NewWorkflowStub<IJDUserSyncWorkflow>(wfo);

 

                      7 var orderTask = stub.JDUserSyncWorkflow(userId);

 

   8 var status = orderTask.result;

 

When it runs, there are 2 cases, when cadence server (GO) return an error and when it returns nill

 

 

When it returns an error: the line line 8 causes an exception, and its inner exception has the error message from GO server

 

When it return nill: the line line 8 causes an exception ((Exception of type 'System.ArgumentNullException' was thrown. (Parameter 'content'))), but no inner exception

 

 

Dear Jeff, how do I check status of the workflow, line 7, without any eceptions?

 


 <http://www.vergeag.com/> 

 	
	
 	

 Kai Osmon   |   IT Senior Solution Architect   |   343-367-6661   |    <mailto:kai.osmon@VergeAg.com> kai.osmon@VergeAg.com

**Comment by jefflill** [comment]
This is a bug (an over aggressive parameter check).  Thanks for the report!

https://github.com/nforgeio/neonKUBE/issues/808

I'm working on a fix and am looking into a unit testing related issue.
I'll probably be able to publish a minor release (v2.0.1) this weekend.

--Jeff

**Comment by jefflill** [comment]
I've fixed #808 and have published a new release:

https://github.com/nforgeio/neonKUBE/releases/tag/v2.0.1

Let me know if you have any more problems.

**Comment by kaiverge** [comment]
Thank you, will test as soon as I can

**Comment by kaiverge** [comment]
did test 2.0.1,   there is no exception now, however, 
 line 8 var status = orderTask.result;
, never returns anything, it stocks on this call.

How do I simply get the status of the worflow?,
 line  7 var orderTask = stub.JDUserSyncWorkflow(userId);
 running / error / etc...?

Maybe its because the workflow is infinite/permanent? We use neon.cadence to trigger Start for the workflow.

**Comment by jefflill** [comment]
The workflow methods in a stub blocks until the workflow completes (or fails) by design (the Java and GOLANG clients do the same).  You can use the [CadenceClient.DescribeWorkflowExecutionAsync()](https://doc.neonkube.com/M_Neon_Cadence_CadenceClient_DescribeWorkflowExecutionAsync.htm) method to obtain the status of a workflow.

The tricky part is that you'll need to know the workflow ID and optionally it's run ID.  If you specified the workflow ID via the optional `WorkflowOptions` passed when you created the stub then you can simply do this to retrieve the status:
```
var status = await client.DescribeWorkflowExecutionAsync("my-workflow-id");
```
If you didn't specify a workflow ID, then Cadence will generate a GUID and use that for the ID and you'll need to be able to obtain the ID Cadence assigned.  You can accomplish this by creating a `WorkflowFutureStub` (instead of a normal stub) like this:
```
// Create a workflow future stub.  The method name should match the name specified in the
// [WorkflowMethod(Name = "my-method")] attribute decorating your workflow interface method
// or you can omit this argument if you didn't specify a name.

var stub = client.NewWorkflowFutureStub<IMyWorkflow>(methodName: "my-method");

// Workflow future stubs are not type safe.  You'll need to call one of the `StartAsync()` overrides to 
// actual start the workflow, specifying the method's result type as a type parameter and passing
// any arguments.  Note that the result type and arguments are not type checked by the C#
// compiler at compile time.  You'll need to take care to ensure that the types and number of
// arguments match your workflow method signature.

var workflowTask = await stub.StartAsync<TResult>(/* Add your workflow args here */);

// Obtain the status of the workflow:

var status = await client.DescribeWorkflowExecutionAsync(stub.Execution.WorkflowId);

// Wait for the workflow to complete and obtain the result:

var result = await workflowTask;
```
Unfortunately, it's not possible to use a typed stub for this situation.

**Comment by kaiverge** [comment]
Hi, will you please tell me the best scenario of doing the following:

1. GO cadence server is running.
2. With Neon.Cadence, I am registering an activity with GO Cadence server.
3. When GO Cadence executes an activity from step 2, the activity runs a specific c# function that returns a text or an error.

How do I implement it.

Currently I do this, will it be enough?

` [ActivityInterface(TaskList = "hello-tasks")]
    public interface IHelloActivity : IActivity
    {
        [ActivityMethod]
        Task<string> HelloAsync(string name);
    }

    [Activity(AutoRegister = true)]
    public class HelloActivity : ActivityBase, IHelloActivity
    {
        public async Task<string> HelloAsync(string name)
        {
            return await Task.FromResult($"Hello {name}!");
        }
    }

public static async Task Main(string[] args)
        {
            try
            {
                var settings = new CadenceSettings("cadence://localhost:7933")
                {
                    DefaultDomain = "test-domain",
                    CreateDomain  = true
                };

                using (var client = await CadenceClient.ConnectAsync(settings))
                {
                    await client.RegisterActivityAsync<HelloActivity>();
                    await client.StartWorkerAsync("my-tasks");
                 }
             }
          }
`
