### ISSUE TITLE
Node fingerprints

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#838]
We need all of the nodes to have the same host SSH key and then persist this in the cluster definition.  This got broken during the SSH configuration.

**Comment by marcusbooyah** [comment]
🤦 there is only 1 issue here, updating above post

**Comment by jefflill** [comment]
Yeah, this is still a pending feature (I think there may already be an issue).

First, SSH from the CLI will depend on manipulating the cluster external load balancer for cloud deployments (since we no longer have the integrated VPN).  I’m not entirely sure that manipulating the LB really makes sense though, ...what if two people happen to want to SSH into nodes at the same time?  We’d have to ensure that any LB changes don’t stomp on each other.

Perhaps proxying SSH would make more sense.  It would be a more general solution.

Also, the old neonHIVE code actually downloaded the cluster configuration from the cluster before any commands like these execute (so I the client could discover node changes).  This was persisted to Consul back in the day.  We’d need to preset this to Etc and have the cluster-manager service service this.

**Comment by jefflill** [comment]
This was re-implemented some time ago.
