### ISSUE TITLE
Ubuntu 20.04 support for neonKUBE clusters

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#839]
It's 2020, we should support the latest LTS release of Ubuntu, assuming we want to stick with it as the base OS.

**Comment by marcusbooyah** [comment]
We might want to look into Fedora CoreOS.

**Comment by jefflill** [comment]
Yeah, we’ll need to think about this.  I’m not sure this is an immediate priority.  I could see sticking with 18.04 for a few months and then re-evaluating.

I would like to figure out whether we can use cloud-init (or something) to configure the node static IPs.  The current solution is a bit clunky (it depends on DHCP being available on the local network) and is pretty slow on XCP.

**Comment by jefflill** [comment]
Maybe.  That would be a really big change.

The nice thing about Kubernetes is that a lot of the base OS details doesn’t matter as much any more.

**Comment by jefflill** [comment]
Here are the release notes:

https://wiki.ubuntu.com/FocalFossa/ReleaseNotes

I skimmed through this and it looks like neonKUBE will require much fewer changes to support this (I remeber the biggest change for the 16.04 --> 18.04) upgrade being the switch to **systemd**; which we won't have here).  Here are the changes I can see potentially impacting us:

* **Python3** is the default now.  Python 2.7 is no longer installed.

* **ZFS**: Should we consider switching from **EXT4**?

* cloud-init now supports detection and support for new datasources: e24cloud, Exoscale, and Zstack.  Perhaps we can use this to solve our IP address assignment performance issue: #451

  e24cloud, Exoscale, and Zstack look like IaaS services but perhaps we can add some kind of driver to our VM templates that can communicate with something in a neonKUBE local cluster to pick up config settings.

**Comment by jefflill** [comment]
https://ubuntu.com/blog/zfs-focus-on-ubuntu-20-04-lts-whats-new

It looks like ZFS is still considered to be experimental, so we're not going to mess with it at this time.  I'm also going to implement a poor man's cloud-init by mounting an ISO including a custom script during cluster node preparation as described in #451.  I don't want to spend the time figuring out cloud-init right now.

**Comment by jefflill** [comment]
There were a couple new problems preparing the node templates for Ubuntu 20.04:

1. `systemd` and `(sd-pam)` processes were still hanging around for a user after that user logged out.  It appears that these are eventually killed but that appears to take some time and the UID for that user cannot be changed and the user can't be removed while these processes are still running.

   I addressed this by explicitly killing the user's processes in the script after logging in as another user.

2. The little script updating the `sysadmin` user's file UID/GIDs was failing for virtual files like `/proc/* and `/task/*`.  This turned out to be due to the processes still running for the user.

**Comment by jefflill** [comment]
This is the first time that we're going to allow folks to have a choice of installing from more than one Ubuntu releases: **18.04** and **20.04**.  Although cluster definitions provide a way to specify the source node template as a URI, we've never actually modified this and have always configured our clusters to use http://s3-us-west-2.amazonaws.com/neonforge/kube/xenserver-ubuntu-18.04.latest.xva for XenServer hosting and https://s3-us-west-2.amazonaws.com/neonforge/kube/hyperv-ubuntu-18.04.latest.vhdx for Hyper-V (cloud uses cloud provided VM images).

It's probably time to clean this up.  Here are a few things I'd like to accomplish:

- [ ] By default, I'd like cluster definitions to be able to specify just the Linux distribution and version rather than the entire URI.  Something like: `18.04.1` or `20.04.latest` and have cluster setup add the rest of the URI.  This will avoid having cluster definitions hard code the server (like the current S3 bucket) which may change in the future.  Eventually, we'll implement the neonKUBE headend service which will dynamically determine the server.

- [ ] I want to add a separate cluster definition setting that specifies the Linux distro so that it will be cleaner to support other distributions in the future.  We'll default this to `ubuntu`.

- [ ] We currently specify the template URIs in the `HyperVOptions`, `LocalHyperVOptions`, and `XenServerOptions`.  I'd like to move the new distro and version properties up to the top level of the cluster definition.

- [ ] XenServer currently has the `TemplateName` setting which is used for naming the persisted VM template.  We should remove this setting and derive the name from the distro and version, something like **neon-ubuntu-20.04,latest**.  The HyperV hosting manager currently caches the VHDX "template".  We should use the same convention for that.

     The XenServer template is currently named **neonkube-***.  Let's shorten that to just **neon-***.  We added the "kube"  a year ago for backwards compatibility, but we've moved on.  Remove the "kube" will help with backwards compatibility with these changes.

**Comment by jefflill** [comment]
DONE for v2.2.0

**Comment by jefflill** [comment]
I'm moving the **linuxDistribution** and **linuxVersion** to the root of the cluster definition (from `HostingOptions`).
