### ISSUE TITLE
neonDESKTOP 1058 port conflict?

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#877]
@granth7: Is seeing neonDESKTOP fail on start up due to a permissions problem with port **1058**.  The desktop is trying to listen here to expose the API neon-cli uses to communicate with the desktop.

This has been working fine on his machine until today and is still working OK on my machine,  Grant is on a Windows Insider release though, so perhaps MSFT did some kind of sneaky update.

We'll have to investigate this.  Perhaps we'll need to choose different ports.

**Comment by granth7** [comment]
To add to this, trying to bind to port **1058** in a standalone ConsoleApp gives:
 `System.Net.Sockets.SocketException: 'An attempt was made to access a socket in a way forbidden by its access permissions.'`

I tried changing the DesktopServicePort to a random port, which allowed neonDesktop to start but when trying to connect to a cluster I get: 

`Neon.Common.ExecuteException: 'Unable to connect to the server: dial tcp 10.100.16.0:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by jefflill** [comment]
Grant was able to fix this by reinstalling Windows.

**Comment by jefflill** [comment]
I'm beginning to wonder if this is problem with the .NET `WebListener` class which wraps the Windows HTTP.SYS API.  Here's the thought:

* HTTP.SYS allows multiple processes to listen for web requests on the same port (as long as the path prefixes are different).
* What if the neonDESKTOP crashed or quit in a way that Windows didn't stop listening on the path.
* Then, the next time neonDESKTOP starts, it would essentially conflict with itself.
* Perhaps this problem lives across system reboots because Windows is actually hibernating and not actually rebooting.

This seems unlikely though.  The way to verify this the next time this happens would be to hold the SHIFT key down while restarting Windows the next time to force a full reboot.

That being said, I kind of doubt this is the case.  Windows really must ensure that resources like this are released when a process terminates.  neonDESKTOP is known to get into a bad state when it encounters problems.  So it's likely this will be addressed after we do a cleanup pass.

**Comment by jefflill** [comment]
I believe this is probably happening due to a neonDESKTOP bug.  I stopped working on the desktop Feb 2019 when it was kind of working or working enough to be somewhat usable.  There were some race conditions at the time which were generally pretty rare when cluster connections were healthy, but caused failures when the cluster was disconnected (e.g. due to a VPN being down).

I believe we're seeing a race condition here.  All of this needs to be cleaned up.  We're going to track that in the original neonDESKTOP issue: #433 and close this.
