### ISSUE TITLE
setup-prep.sh is failing intermittently

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#890]
I ran it manually and got this error:

>root@ubuntu:~# /lib/neonkube/setup/setup-prep.sh
Warning: Stopping apt-daily.service, but it can still be activated by:
  apt-daily.timer
** Configuring Dialog
apt-get update -yq
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
apt-get install -yq --allow-downgrades unzip
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 5418 (u                                       nattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is an                                       other process using it?

I'm not exactly sure what was running here, but the script should be more robust, and maybe wait for the lock to be removed.

**Comment by jefflill** [comment]
I’ll look into it.  I probable need to mask the service rather then
disabling it.

—Jeff

**Comment by jefflill** [comment]
The first part is just a warning and we disable the **apt-timer** service on the next line which should be enough to prevent this from running automatically in the future.  I did change this script to mask both services to get rid of the warning and REALLY prevent these from running in the future.  This change was pushed to **master**.

Waiting for the lock to be released in **safe-apt.sh** is a good idea but the script is already supposed to retry until it works.  Waiting for the file lock may still not work, because there's a brief window between seeing that the lock is free and initiating the `apt-get install ...` where the update service could grab the lock again.

I added an additional check for `"E: Could not get lock /var/lib/dpkg/lock-frontend."` in the command output and treat that as a transient error that will be retried.

@marcusbooyah: you can leave the lock check in though.  That could be useful to block `setup-prep.sh` until any system updating (which we really don't want to happen) has completed.  There could be the odd case where updating takes a really long time (e.g. a slow network) which is too long even for the safe-apt retries.

**Comment by jefflill** [comment]
You know, on second thought, I'm going to relocate code disabling these apt services to the script run the first time the node boots after being provisioned--before the network is configured.  The nice thing about doing this is that there never will be an opportunity for updates to be applied.

**Comment by jefflill** [comment]
I've pushed my changes the **master**.

**Comment by jefflill** [comment]
FIXED for v2.2.0
