### ISSUE TITLE
Implement IntegerEnumConverter<TEnum> (for JSON.NET)

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#942]
@johncburns1: needs a JSON property converter that converts between integers and enumerations for the Temporal port.

We'll create a new `Neon.Data.IntegerEnumConverter<TEnum>` type within **Neon.Common**.  Note that this will also handle string values as well.

Here's an example using this to decorate a property:
```
using Neon.Data;

public enum MyEnum
{
    Zero = 0,
    One = 1,
    Two = 2
}

public class MyData
{
    [JsonConverter(typeof(IntegerEnumConverter<MyEnum>))]
    public MyEnum Value { get; set; }
}
```

**Comment by jefflill** [comment]
**DONE** for v2.2.0

**Comment by johncburns1** [comment]
Thanks!

**Comment by johncburns1** [comment]
I am not seeing the desired behavior during serialization when implemented using the attribute tag mentioned above.  Decorated enums still come to the proxy as their member strings.  Maybe there is another step to the implementation that I am missing.

**Comment by jefflill** [comment]
I added some unit tests for this.  You can compare those to what you’re
seeing.

—Jeff

**Comment by jefflill** [comment]
One difference might be that the message serializer is probably using the
default NeonHelper JsonSerializer with a setting that serializizes enums as
strings and perhaps that has priority over serializers attached to the
property (which would seem wrong).

We might need to use a new serializer.  I assume that go will expect all
enums to be serialized as ints, correct?

**Comment by johncburns1** [comment]
yes this is correct.

**Comment by johncburns1** [comment]
I am not seeing any test cases in which the backing `int` value of an `Enum` is written to JSON.  Is this a case that this converter covers? When looking through the source, it looks like `Enum` values are always written to the `JsonWriter` using the `NeonHelper.EnumToString()` function.  This function should get the `int` values and write them to the `JsonWriter`.  

When using the converter with `WorkflowIdReusePolicy`, the following code is executed as described below:
```
var info = GetEnumMembers<TEnum>();

if (info.EnumToOrdinals.TryGetValue(Convert.ToInt64(input), out var value))
{
    return value;
}
```

No enum members are found, causing the if statement to evaluate to false, and so the input key name of the `Enum` is always written instead of the `int` value.

**Comment by jefflill** [comment]
This was my bad.  Fixed now.
