### ISSUE TITLE
Serialization of TimeSpan properties in Neon.Temporal

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#947]
Any `TimeSpan` property of a more complex type (i.e. **StickyScheduleToStartTimeout** in `WorkerOptions` needs to be a `long` representing the `TimeSpan` as nanoseconds.  We have a custom converter for deserializing top level time durations properties on the proxy side, but when they are nested in more complex structs, that custom converter cannot be applied.  I know that we are actually doing something similar with top level time duration properties (passing them over as int values and then converting them into nanosecond "ticks").  We probably need to just pass any nested time duration as the duration in nanoseconds.  I have made this change in `WorkerOptions` for the properties **StickyScheduleToStartTimeout** and **WorkerStopTimeout**.

Something to maybe think about is whether we want to keep the time duration properties as `TimeSpan` types on the .NET side and do the conversion when the properties are being serialized.  This might make it easier for users to conceptualize these values.  On the other hand if we just make them all `long` values and well document what they represent, I think that is a pretty standard way to operate as well.

**Comment by jefflill** [comment]
I don't want to expose a `long` for this to .NET users, when .NET has `TimeSpan` that abstracts this so nicely.

The first question will be what's the unit.  We'd say nanoseconds and then probably want to change the property names to include the units to be clear (like `StickyScheduleToStartTimeoutNanoseconds`, `StickyScheduleToStartTimeoutNs`, or something).

Then users start using this and code something like:
```
// Set: StartToCloseTime = 1 sec

var options = new WorkflowOptions()
{
   StartToCloseTimeOut = 100000000L
};
```
Is that correct?  Actually no because it's missing a zero, this specifies 100ms.

...not super developer friendly

So GO doesn't really implement type converters, huh?  Seems like an unfortunate gap.  I wonder how folks write programs that need to interact with services written in other languages that serialize types differently?

We should chat about this.  I suppose we could put the burden back on the .NET side.  Another approach would be to stop using JSON properties and just encode everything in the messages themselves.

**Comment by jefflill** [comment]
Another approach would be to manually decode the types we need to on the GO side as unstructured data (Decoding JSON to maps) and then map the values to the actual Temporal GO structure.

https://www.sohamkamani.com/blog/2017/10/18/parsing-json-in-golang/

...search for **Decoding JSON to maps**

I think I'd prefer this approach it it's not too much of a pain.  Trying to mimic GO behavior on the .NET side was really a bit of a mess for Cadence.

**Comment by jefflill** [comment]
Closing this because @johncburns1 is handling this as part of the Temporal port.
