### ISSUE TITLE
Hyper-V, XenServer: Verify host machine CPU, DISK and RAM

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#994]
- [ ] We should check that the Hypervisor hosts have enough resources to deploy the cluster before we actually do it.
- [ ] Also verify that new node VMs don't conflict with any existing VMs

**Comment by jefflill** [comment]
This might be a bit tricky for XenServer, especially if its using one ore more non-local storage repositories.

I'm not entirely sure that this is worthwhile for local Hyper-V since we're using the dynamic RAM option and I'm pretty sure we're doing the same for disks.  We'll probably want to do this for Windows Server Hyper-V though.

I'm putting this on the backlog.

**Comment by marcusbooyah** [comment]
DONE
